AllCops:
  Exclude:
    - vendor/**/*

inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Style/FileName:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent
