before_install:
  - gem update --system
  - gem install bundler

after_success:
  - bundle exec danger

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6

env:
  - GRAPE_ENTITY=0.5.2
  - GRAPE_ENTITY=0.6.1

matrix:
  fast_finish: true

  include:
    - rvm: ruby-head
      env:
    - rvm: jruby-head
      env:
    - rvm: rbx-2
      env:

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
