language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.3.0
      script:
        - bundle exec danger
    - rvm: 2.3.0
      env:
        - GRAPE_ENTITY="~> 0.4.0"
    - rvm: 2.3.0
      env:
        - GRAPE_ENTITY="~> 0.5.0"
    - rvm: 2.3.0
      env:
        - GRAPE_ENTITY="~> 0.6.0"
    - rvm: 2.2
    - rvm: 2.1
    - rvm: jruby-9.1.2.0
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

before_install: gem install bundler -v 1.12.1
